stdout: {}
stderr: |
  docker: Error response from daemon: received unexpected HTTP status: 500 Internal Server Error

  Run 'docker run --help' for more information
exitcode: 125
cmd: docker run --pull always --rm -v trivy-db:/root/.cache/trivy aquasec/trivy -f json  image nmaguiar/d3k:latest
