name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'
  schedule:
    - cron: '28 0 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
      name: Checkout
    - uses: docker/build-push-action@v6
      name: Build and push
      with:
        platforms: linux/amd64,linux/arm64
        context: "{{defaultContext}}"
        push: true
        tags: nmaguiar/d3k:build
        file: Dockerfile
